source_catalog: "vcn-federated"
tables:
  # --- SCHEMA: financial_manager ---
  - name: "account_payable"
    schema: "financial_manager"
  - name: "account_payable_detail"
    schema: "financial_manager"
  - name: "batch_account_payable"
    schema: "financial_manager"

  # --- SCHEMA: public ---
  - name: "agency"
    schema: "public"
  - name: "air"
    schema: "public"
  - name: "api_key_user"
    schema: "public"
  - name: "app"
    schema: "public"
  - name: "app_terms"
    schema: "public"
  - name: "attachment"
    schema: "public"
  - name: "attachment_entity"
    schema: "public"
  - name: "attribute"
    schema: "public"
  - name: "bank"
    schema: "public"
  - name: "bank_slip"
    schema: "public"
  - name: "car_rental"
    schema: "public"
  - name: "card_brand"
    schema: "public"
  - name: "city"
    schema: "public"
  - name: "comp_group_srv_provider_rcn"
    schema: "public"
  - name: "company"
    schema: "public"
  - name: "company_div_system_user"
    schema: "public"
  - name: "company_division"
    schema: "public"
  - name: "company_division_group"
    schema: "public"
  - name: "company_group"
    schema: "public"
  - name: "company_group_srv_provider"
    schema: "public"
  - name: "company_relation"
    schema: "public"
  - name: "company_released"
    schema: "public"
  - name: "company_system_user"
    schema: "public"
  - name: "company_type"
    schema: "public"
  - name: "company_vcn_provider_bank"
    schema: "public"
  - name: "counter"
    schema: "public"
  - name: "country"
    schema: "public"
  - name: "customer"
    schema: "public"
  - name: "customer_agency_user_access"
    schema: "public"
  - name: "hotel"
    schema: "public"
  - name: "merchant_category_code"
    schema: "public"
  - name: "permission"
    schema: "public"
  - name: "person"
    schema: "public"
  - name: "person_address"
    schema: "public"
  - name: "person_mail"
    schema: "public"
  - name: "person_phone"
    schema: "public"
  - name: "product"
    schema: "public"
  - name: "product_attribute"
    schema: "public"
  - name: "product_category"
    schema: "public"
  - name: "product_sub_category"
    schema: "public"
  - name: "real_card"
    schema: "public"
  - name: "real_card_financial_data"
    schema: "public"
  - name: "role"
    schema: "public"
  - name: "role_permission"
    schema: "public"
  - name: "service_async_process"
    schema: "public"
  - name: "srv_contractor_rcn_user"
    schema: "public"
  - name: "srv_contractor_system_user"
    schema: "public"
  - name: "state"
    schema: "public"
  - name: "supplier"
    schema: "public"
  - name: "system_user"
    schema: "public"
  - name: "system_user_role"
    schema: "public"
  - name: "translation_code"
    schema: "public"
  - name: "user_vcn_draft_approval_val"
    schema: "public"
  - name: "vcn_access_token"
    schema: "public"
  - name: "vcn_access_token_recipient"
    schema: "public"
  - name: "vcn_access_token_record"
    schema: "public"
  - name: "vcn_control_group"
    schema: "public"
  - name: "vcn_provider"
    schema: "public"
  - name: "vcn_provider_bank"
    schema: "public"
  - name: "vcn_provider_card_brand"
    schema: "public"
  - name: "vcn_request"
    schema: "public"
  - name: "vcn_request_draft"
    schema: "public"
  - name: "vcn_request_draft_state"
    schema: "public"
  - name: "vcn_request_financial_trans"
    schema: "public"
  - name: "vcn_request_message"
    schema: "public"
  - name: "vcn_request_supplier"
    schema: "public"
  - name: "vcn_template"
    schema: "public"
  - name: "vcn_template_field"
    schema: "public"