source_catalog: "vcn-federated"

# Valores padrão para economizar linhas (seu código Python lê 'defaults')
defaults:
  strategy: "snapshot" 
  # "snapshot" = Full Load (Prod) ou Limit 100k (Dev)

tables:
  - name: "anexo"
    schema: "b2b"

  - name: "anexo_registro"
    schema: "b2b"

  - name: "cidade"
    schema: "b2b"

  - name: "empresa"
    schema: "b2b"

  - name: "hotel"
    schema: "b2b"

  - name: "metadado"
    schema: "b2b"

  - name: "pessoa"
    schema: "b2b"

  - name: "reserva"
    schema: "b2b"

  - name: "reserva_cartao_virtual"
    schema: "b2b"

  - name: "reserva_cartao_virtual_item"
    schema: "b2b"

  - name: "reserva_conciliacao"
    schema: "b2b"

  - name: "reserva_conciliacao_parcial"
    schema: "b2b"

  - name: "tradutor"
    schema: "b2b"

  - name: "usuario_empresa"
    schema: "b2b"