source_catalog: "b2b-federated"

tables:
  - name: "agreement"
    schema: "agency"
    pk: "agreement_id"
    watermark: "last_modified"

  - name: "agreement_company"
    schema: "agency"
    pk: "company_agreement_id"
    watermark: "last_modified"

  - name: "agreement_company_payment"
    schema: "agency"
    pk: "agreement_company_payment_id"
    watermark: "last_modified"

  - name: "allotment_request"
    schema: "agency"
    pk: "allotment_request_id"
    watermark: "last_modified"

  - name: "allotment_request_item"
    schema: "agency"
    pk: "allotment_request_item_id"
    watermark: "last_modified"

  - name: "batch_booking"
    schema: "agency"
    pk: "batch_booking_id"
    watermark: "last_modified"

  - name: "batch_booking_layout"
    schema: "agency"
    pk: "batch_booking_layout_id"
    watermark: "last_modified"

  - name: "batch_booking_process"
    schema: "agency"
    pk: "batch_booking_process_id"
    watermark: "last_modified"

  - name: "batch_booking_process_log"
    schema: "agency"
    pk: "batch_booking_process_log_id"
    watermark: "last_modified"

  - name: "batch_booking_request"
    schema: "agency"
    pk: "batch_booking_request_id"
    watermark: "last_modified"

  - name: "batch_booking_request_log"
    schema: "agency"
    pk: "batch_booking_rerquest_log_id"
    watermark: "last_modified"

  - name: "booking"
    schema: "agency"
    pk: "booking_id"
    watermark: "last_modified"

  - name: "booking_agency"
    schema: "agency"
    pk: "booking_agency_id"
    watermark: "last_modified"

  - name: "booking_change_request"
    schema: "agency"
    pk: "booking_change_request_id"
    watermark: "last_modified"

  - name: "booking_guest"
    schema: "agency"
    pk: "booking_guest_id"
    watermark: "last_modified"

  - name: "booking_room_rate"
    schema: "agency"
    pk: "booking_room_rate_id"
    watermark: "last_modified"

  - name: "booking_room_type"
    schema: "agency"
    pk: "booking_room_type_id"
    watermark: "last_modified"

  - name: "booking_slip"
    schema: "agency"
    pk: "booking_slip_id"
    watermark: "last_modified"

  - name: "booking_tax_type"
    schema: "agency"
    pk: "booking_tax_type_id"
    watermark: "last_modified"

  - name: "business_sector"
    schema: "agency"
    pk: "business_sector_id"
    watermark: "last_modified"

  - name: "city"
    schema: "agency"
    pk: "city_id"
    watermark: "last_modified"

  - name: "company"
    schema: "agency"
    pk: "company_id"
    watermark: "last_modified"

  - name: "company_address"
    schema: "agency"
    pk: "company_address_id"
    watermark: "last_modified"

  - name: "company_center_cost"
    schema: "agency"
    pk: "company_center_cost_id"
    watermark: "last_modified"

  - name: "company_chain_profile"
    schema: "agency"
    pk: "company_chain_profile_id"
    watermark: "last_modified"

  - name: "company_contact"
    schema: "agency"
    pk: "company_contact_id"
    watermark: "last_modified"

  - name: "company_contract"
    schema: "agency"
    pk: "company_contract_id"
    watermark: "last_modified"

  - name: "company_custom_field"
    schema: "agency"
    pk: "company_custom_field_id"
    watermark: "last_modified"

  - name: "company_custom_field_type"
    schema: "agency"
    pk: "company_custom_field_type_id"
    watermark: "last_modified"

  - name: "company_customer"
    schema: "agency"
    pk: "company_customer_id"
    watermark: "last_modified"

  - name: "company_group"
    schema: "agency"
    pk: "company_group_id"
    watermark: "last_modified"

  - name: "company_policy"
    schema: "agency"
    pk: "company_policy_id"
    watermark: "last_modified"

  - name: "company_policy_data"
    schema: "agency"
    pk: "company_policy_data_id"
    watermark: "last_modified"

  - name: "company_policy_definition"
    schema: "agency"
    pk: "company_policy_definition_id"
    watermark: "last_modified"

  - name: "company_policy_hotel"
    schema: "agency"
    pk: "company_policy_hotel_id"
    watermark: "last_modified"

  - name: "company_policy_use"
    schema: "agency"
    pk: "company_policy_use_id"
    watermark: "last_modified"

  - name: "company_rcn"
    schema: "agency"
    pk: "company_rcn_id"
    watermark: "last_modified"

  - name: "company_type"
    schema: "agency"
    pk: "company_type_code"
    watermark: "last_modified"

  - name: "country"
    schema: "agency"
    pk: "country_id"
    watermark: "last_modified"

  - name: "credit_card"
    schema: "agency"
    pk: "credit_card_id"
    watermark: "last_modified"

  - name: "credit_card_brand"
    schema: "agency"
    pk: "credit_card_brand_id"
    watermark: "last_modified"

  - name: "currency"
    schema: "agency"
    pk: "currency_id"
    watermark: "last_modified"

  - name: "department"
    schema: "agency"
    pk: "department_code"
    watermark: "last_modified"

  - name: "distribution"
    schema: "agency"
    pk: "distribution_id"
    watermark: "last_modified"

  - name: "distribution_channel"
    schema: "agency"
    pk: "distribution_channel_id"
    watermark: "last_modified"

  - name: "distribution_channel_pms"
    schema: "agency"
    pk: "distribution_channel_pms_id"
    watermark: "last_modified"

  - name: "distribution_pms_code"
    schema: "agency"
    pk: "distribution_pms_code_id"
    watermark: "last_modified"

  - name: "expense_type"
    schema: "agency"
    pk: "expense_type_id"
    watermark: "last_modified"

  - name: "meal_plan"
    schema: "agency"
    pk: "meal_plan_id"
    watermark: "last_modified"

  - name: "payment_method"
    schema: "agency"
    pk: "payment_method_id"
    watermark: "last_modified"

  - name: "pms"
    schema: "agency"
    pk: "pms_id"
    watermark: "last_modified"

  - name: "policy_category"
    schema: "agency"
    pk: "policy_category_id"
    watermark: "last_modified"

  - name: "rcn"
    schema: "agency"
    pk: "rcn_id"
    watermark: "last_modified"

  - name: "slip_customization"
    schema: "agency"
    pk: "slip_customization_id"
    watermark: "last_modified"

  - name: "slip_section"
    schema: "agency"
    pk: "slip_section_id"
    watermark: "last_modified"

  - name: "state"
    schema: "agency"
    pk: "state_id"
    watermark: "last_modified"

  - name: "subscription_plan"
    schema: "agency"
    pk: "subscription_plan_id"
    watermark: "last_modified"

  - name: "system_user"
    schema: "agency"
    pk: "system_user_id"
    watermark: "last_modified"

  - name: "tour_agency"
    schema: "agency"
    pk: "code"
    watermark: "last_modified"

  - name: "user_company"
    schema: "agency"
    pk: "user_company_id"
    watermark: "last_modified"

  - name: "vcn_company"
    schema: "agency"
    pk: "vcn_company_id"
    watermark: "last_modified"

  # --- SCHEMA: public ---
  - name: "agency"
    schema: "public"
    pk: "agency_id"
    watermark: "last_modified"

  - name: "air"
    schema: "public"
    pk: "air_id"
    watermark: "last_modified"

  - name: "api_key_user"
    schema: "public"
    pk: "api_key_user_id"
    watermark: "last_modified"

  - name: "app"
    schema: "public"
    pk: "app_id"
    watermark: "last_modified"

  - name: "app_terms"
    schema: "public"
    pk: "app_terms_id"
    watermark: "last_modified"

  - name: "attachment"
    schema: "public"
    pk: "attachment_id"
    watermark: "last_modified"

  - name: "attachment_entity"
    schema: "public"
    pk: "attachment_entity_id"
    watermark: "last_modified"

  - name: "attribute"
    schema: "public"
    pk: "attribute_id"
    watermark: "last_modified"

  - name: "bank"
    schema: "public"
    pk: "bank_id"
    watermark: "last_modified"

  - name: "bank_slip"
    schema: "public"
    pk: "bank_slip_id"
    watermark: "last_modified"

  - name: "car_rental"
    schema: "public"
    pk: "car_rental_id"
    watermark: "last_modified"

  - name: "card_brand"
    schema: "public"
    pk: "card_brand_id"
    watermark: "last_modified"

  - name: "city"
    schema: "public"
    pk: "city_id"
    watermark: "last_modified"

  - name: "company"
    schema: "public"
    pk: "company_id"
    watermark: "last_modified"

  - name: "company_div_system_user"
    schema: "public"
    pk: "company_div_system_user_id"
    watermark: "last_modified"

  - name: "company_division"
    schema: "public"
    pk: "company_division_id"
    watermark: "last_modified"

  - name: "company_division_group"
    schema: "public"
    pk: "company_division_group_id"
    watermark: "last_modified"

  - name: "company_group"
    schema: "public"
    pk: "company_group_id"
    watermark: "last_modified"

  - name: "company_group_srv_provider"
    schema: "public"
    pk: "company_group_srv_provider_id"
    watermark: "last_modified"

  - name: "company_relation"
    schema: "public"
    pk: "company_relation_id"
    watermark: "last_modified"

  - name: "company_released"
    schema: "public"
    pk: "company_released_id"
    watermark: "last_modified"

  - name: "company_system_user"
    schema: "public"
    pk: "company_system_user_id"
    watermark: "last_modified"

  - name: "company_type"
    schema: "public"
    pk: "company_type_id"
    watermark: "last_modified"

  - name: "company_vcn_provider_bank"
    schema: "public"
    pk: "company_vcn_provider_bank_id"
    watermark: "last_modified"

  - name: "counter"
    schema: "public"
    pk: "counter_id"
    watermark: "last_modified"

  - name: "country"
    schema: "public"
    pk: "country_id"
    watermark: "last_modified"

  - name: "customer"
    schema: "public"
    pk: "customer_id"
    watermark: "last_modified"

  - name: "customer_agency_user_access"
    schema: "public"
    pk: "customer_agency_user_access_id"
    watermark: "last_modified"

  - name: "hotel"
    schema: "public"
    pk: "hotel_id"
    watermark: "last_modified"

  - name: "merchant_category_code"
    schema: "public"
    pk: "merchant_category_code_id"
    watermark: "last_modified"

  - name: "permission"
    schema: "public"
    pk: "permission_id"
    watermark: "last_modified"

  - name: "person"
    schema: "public"
    pk: "person_id"
    watermark: "last_modified"

  - name: "person_address"
    schema: "public"
    pk: "person_address_id"
    watermark: "last_modified"

  - name: "person_mail"
    schema: "public"
    pk: "person_mail_id"
    watermark: "last_modified"

  - name: "person_phone"
    schema: "public"
    pk: "person_phone_id"
    watermark: "last_modified"

  - name: "product"
    schema: "public"
    pk: "product_id"
    watermark: "last_modified"

  - name: "product_attribute"
    schema: "public"
    pk: "product_attribute_id"
    watermark: "last_modified"

  - name: "product_category"
    schema: "public"
    pk: "product_category_id"
    watermark: "last_modified"

  - name: "product_sub_category"
    schema: "public"
    pk: "product_sub_category_id"
    watermark: "last_modified"

  - name: "real_card"
    schema: "public"
    pk: "real_card_id"
    watermark: "last_modified"

  - name: "real_card_financial_data"
    schema: "public"
    pk: "real_card_financial_data_id"
    watermark: "last_modified"

  - name: "role"
    schema: "public"
    pk: "role_id"
    watermark: "last_modified"

  - name: "role_permission"
    schema: "public"
    pk: "role_permission_id"
    watermark: "last_modified"

  - name: "service_async_process"
    schema: "public"
    pk: "service_async_process_id"
    watermark: "last_modified"

  - name: "srv_contractor_rcn_user"
    schema: "public"
    pk: "srv_contractor_rcn_user_id"
    watermark: "last_modified"

  - name: "srv_contractor_system_user"
    schema: "public"
    pk: "srv_contractor_system_user_id"
    watermark: "last_modified"

  - name: "state"
    schema: "public"
    pk: "state_id"
    watermark: "last_modified"

  - name: "supplier"
    schema: "public"
    pk: "supplier_id"
    watermark: "last_modified"

  - name: "system_user"
    schema: "public"
    pk: "system_user_id"
    watermark: "last_modified"

  - name: "system_user_role"
    schema: "public"
    pk: "system_user_role_id"
    watermark: "last_modified"

  - name: "translation_code"
    schema: "public"
    pk: "translation_code_id"
    watermark: "last_modified"

  - name: "user_vcn_draft_approval_val"
    schema: "public"
    pk: "user_vcn_draft_approval_val_id"
    watermark: "last_modified"

  - name: "vcn_access_token"
    schema: "public"
    pk: "vcn_access_token_id"
    watermark: "last_modified"

  - name: "vcn_access_token_recipient"
    schema: "public"
    pk: "vcn_access_token_recipient_id"
    watermark: "last_modified"

  - name: "vcn_access_token_record"
    schema: "public"
    pk: "vcn_access_token_record_id"
    watermark: "last_modified"

  - name: "vcn_control_group"
    schema: "public"
    pk: "vcn_control_group_id"
    watermark: "last_modified"

  - name: "vcn_provider"
    schema: "public"
    pk: "vcn_provider_id"
    watermark: "last_modified"

  - name: "vcn_provider_bank"
    schema: "public"
    pk: "vcn_provider_bank_id"
    watermark: "last_modified"

  - name: "vcn_provider_card_brand"
    schema: "public"
    pk: "vcn_provider_card_brand_id"
    watermark: "last_modified"

  - name: "vcn_request"
    schema: "public"
    pk: "vcn_request_id"
    watermark: "last_modified"

  - name: "vcn_request_draft"
    schema: "public"
    pk: "vcn_request_draft_id"
    watermark: "last_modified"

  - name: "vcn_request_financial_trans"
    schema: "public"
    pk: "vcn_request_financial_trans_id"
    watermark: "last_modified"

  - name: "vcn_template"
    schema: "public"
    pk: "vcn_template_id"
    watermark: "last_modified"

  - name: "vcn_template_field"
    schema: "public"
    pk: "vcn_template_field_id"
    watermark: "last_modified"

  # --- SCHEMA: ex_content ---
  - name: "content_history"
    schema: "ex_content"

  - name: "hotel_content_expedia"
    schema: "ex_content"

  - name: "hotel_content_expedia_old"
    schema: "ex_content"

  - name: "hotel_content_expedia_raw"
    schema: "ex_content"

  - name: "hotel_content_trend_25_01_2024"
    schema: "ex_content"
